version: '3.8'

services:
  frontend:
    image: myapp/frontend:latest
    container_name: frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    image: myapp/backend:latest
    container_name: backend
    ports:
      - '3001:3001'
    depends_on:
      - db

  db:
    image: myapp/database:latest
    container_name: database
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
