services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    image: myapp:dev
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    image: myapp:prod